name: Debian package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install -y devscripts equivs
    - name: Build Dependencies
      run: sudo mk-build-deps -ir
    - name: Build packages
      run: debuild -i -us -uc -b
